name: Build All

on:
  workflow_dispatch:

jobs:

  linux:
    name: Build Linux
    uses: ./.github/workflows/build-linux.yml

  android:
    name: Build Android
    uses: ./.github/workflows/build-android.yml

  windows:
    name: Build Windows
    uses: ./.github/workflows/build-windows.yml

  macos:
    name: Build macOS
    uses: ./.github/workflows/build-macos.yml

  ios:
    name: Build iOS
    uses: ./.github/workflows/build-ios.yml